---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01e7gh1vnsmkrfkfs5bjywmka9"
    - from: "jfmd@*"
      to: "jfmd@01e7gh1za6qz2t4vmqtcnbe4vr"
    - from: "jfrt@*"
      to: "jfrt@01e7gh2d0pr6jb13k3zmwt0tvb"
    - from: "jffe@*"
      to: "jffe@000"
