package fr.unice.polytech.si._4a.isa.dd.team_h.rating;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-04-24T12:19:03.503+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", name = "CommentPostingWebService")
@XmlSeeAlso({fr.unice.polytech.si._4a.isa.dd.team_h.packages.ObjectFactory.class, ObjectFactory.class, stubs.ratings.ObjectFactory.class})
public interface CommentPostingWebService {

    @WebMethod
    @RequestWrapper(localName = "findAllComments", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.FindAllComments")
    @ResponseWrapper(localName = "findAllCommentsResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.FindAllCommentsResponse")
    @WebResult(name = "comment_list", targetNamespace = "")
    public java.util.List<fr.unice.polytech.si._4a.isa.dd.team_h.rating.Comment> findAllComments();

    @WebMethod
    @RequestWrapper(localName = "createComment", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.CreateComment")
    @ResponseWrapper(localName = "createCommentResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.CreateCommentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public fr.unice.polytech.si._4a.isa.dd.team_h.rating.Comment createComment(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber,
        @WebParam(name = "rating", targetNamespace = "")
        int rating,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    ) throws UnknownDeliveryException;

    @WebMethod
    @RequestWrapper(localName = "deleteComment", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.DeleteComment")
    @ResponseWrapper(localName = "deleteCommentResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.DeleteCommentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteComment(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber
    ) throws UnknownCommentException_Exception, UnknownDeliveryException;

    @WebMethod
    @RequestWrapper(localName = "findCommentForPackage", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.FindCommentForPackage")
    @ResponseWrapper(localName = "findCommentForPackageResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.FindCommentForPackageResponse")
    @WebResult(name = "comment", targetNamespace = "")
    public fr.unice.polytech.si._4a.isa.dd.team_h.rating.Comment findCommentForPackage(
        @WebParam(name = "packageId", targetNamespace = "")
        java.lang.String packageId
    ) throws UnknownCommentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findCommentForSupplier", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.FindCommentForSupplier")
    @ResponseWrapper(localName = "findCommentForSupplierResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "fr.unice.polytech.si._4a.isa.dd.team_h.rating.FindCommentForSupplierResponse")
    @WebResult(name = "supplier_comments", targetNamespace = "")
    public java.util.List<fr.unice.polytech.si._4a.isa.dd.team_h.rating.Comment> findCommentForSupplier(
        @WebParam(name = "supplierName", targetNamespace = "")
        java.lang.String supplierName
    ) throws UnknownSupplierException;
}
