
package fr.unice.polytech.si._4a.isa.dd.team_h.rating;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-04-24T18:19:22.904+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownCommentException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating")
public class UnknownCommentException_Exception extends Exception {
    
    private fr.unice.polytech.si._4a.isa.dd.team_h.rating.UnknownCommentException unknownCommentException;

    public UnknownCommentException_Exception() {
        super();
    }
    
    public UnknownCommentException_Exception(String message) {
        super(message);
    }
    
    public UnknownCommentException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownCommentException_Exception(String message, fr.unice.polytech.si._4a.isa.dd.team_h.rating.UnknownCommentException unknownCommentException) {
        super(message);
        this.unknownCommentException = unknownCommentException;
    }

    public UnknownCommentException_Exception(String message, fr.unice.polytech.si._4a.isa.dd.team_h.rating.UnknownCommentException unknownCommentException, Throwable cause) {
        super(message, cause);
        this.unknownCommentException = unknownCommentException;
    }

    public fr.unice.polytech.si._4a.isa.dd.team_h.rating.UnknownCommentException getFaultInfo() {
        return this.unknownCommentException;
    }
}
