
package fr.unice.polytech.si._4a.isa.dd.team_h.rating;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-04-29T12:04:53.659+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownDeliveryException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/accounting")
public class UnknownDeliveryException extends Exception {
    
    private stubs.ratings.UnknownDeliveryException unknownDeliveryException;

    public UnknownDeliveryException() {
        super();
    }
    
    public UnknownDeliveryException(String message) {
        super(message);
    }
    
    public UnknownDeliveryException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDeliveryException(String message, stubs.ratings.UnknownDeliveryException unknownDeliveryException) {
        super(message);
        this.unknownDeliveryException = unknownDeliveryException;
    }

    public UnknownDeliveryException(String message, stubs.ratings.UnknownDeliveryException unknownDeliveryException, Throwable cause) {
        super(message, cause);
        this.unknownDeliveryException = unknownDeliveryException;
    }

    public stubs.ratings.UnknownDeliveryException getFaultInfo() {
        return this.unknownDeliveryException;
    }
}
