
package fr.unice.polytech.si._4a.isa.dd.team_h.rating;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-04-24T12:19:03.499+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownSupplierException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages")
public class UnknownSupplierException extends Exception {
    
    private fr.unice.polytech.si._4a.isa.dd.team_h.packages.UnknownSupplierException unknownSupplierException;

    public UnknownSupplierException() {
        super();
    }
    
    public UnknownSupplierException(String message) {
        super(message);
    }
    
    public UnknownSupplierException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownSupplierException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.packages.UnknownSupplierException unknownSupplierException) {
        super(message);
        this.unknownSupplierException = unknownSupplierException;
    }

    public UnknownSupplierException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.packages.UnknownSupplierException unknownSupplierException, Throwable cause) {
        super(message, cause);
        this.unknownSupplierException = unknownSupplierException;
    }

    public fr.unice.polytech.si._4a.isa.dd.team_h.packages.UnknownSupplierException getFaultInfo() {
        return this.unknownSupplierException;
    }
}
