
package stubs.planning;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T13:25:09.729+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "DeliveryDistanceException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/accounting/planning")
public class DeliveryDistanceException extends Exception {
    
    private fr.unice.polytech.si._4a.isa.dd.team_h.accounting.planning.DeliveryDistanceException deliveryDistanceException;

    public DeliveryDistanceException() {
        super();
    }
    
    public DeliveryDistanceException(String message) {
        super(message);
    }
    
    public DeliveryDistanceException(String message, Throwable cause) {
        super(message, cause);
    }

    public DeliveryDistanceException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.accounting.planning.DeliveryDistanceException deliveryDistanceException) {
        super(message);
        this.deliveryDistanceException = deliveryDistanceException;
    }

    public DeliveryDistanceException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.accounting.planning.DeliveryDistanceException deliveryDistanceException, Throwable cause) {
        super(message, cause);
        this.deliveryDistanceException = deliveryDistanceException;
    }

    public fr.unice.polytech.si._4a.isa.dd.team_h.accounting.planning.DeliveryDistanceException getFaultInfo() {
        return this.deliveryDistanceException;
    }
}
