package stubs.planning;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-14T19:22:05.751+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "PlanningWebServiceImplService", 
                  wsdlLocation = "file:/C:/Users/Triagon/Desktop/Work/Polytech/ISA-DevOps/DevOps/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/resources/PlanningWebServiceImpl.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning") 
public class PlanningWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning", "PlanningWebServiceImplService");
    public final static QName PlanningWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning", "PlanningWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Triagon/Desktop/Work/Polytech/ISA-DevOps/DevOps/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/resources/PlanningWebServiceImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PlanningWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Triagon/Desktop/Work/Polytech/ISA-DevOps/DevOps/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/resources/PlanningWebServiceImpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PlanningWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PlanningWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlanningWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PlanningWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PlanningWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PlanningWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PlanningWebService
     */
    @WebEndpoint(name = "PlanningWebServiceImplPort")
    public PlanningWebService getPlanningWebServiceImplPort() {
        return super.getPort(PlanningWebServiceImplPort, PlanningWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlanningWebService
     */
    @WebEndpoint(name = "PlanningWebServiceImplPort")
    public PlanningWebService getPlanningWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PlanningWebServiceImplPort, PlanningWebService.class, features);
    }

}
