package stubs.planning;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-14T19:22:05.736+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning", name = "PlanningWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PlanningWebService {

    @WebMethod
    @RequestWrapper(localName = "getCompleteDeliveryPlanning", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning", className = "stubs.planning.GetCompleteDeliveryPlanning")
    @ResponseWrapper(localName = "getCompleteDeliveryPlanningResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning", className = "stubs.planning.GetCompleteDeliveryPlanningResponse")
    @WebResult(name = "delivery-planning", targetNamespace = "")
    public java.util.List<stubs.planning.PlanningEntry> getCompleteDeliveryPlanning();

    @WebMethod
    @RequestWrapper(localName = "planDelivery", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning", className = "stubs.planning.PlanDelivery")
    @ResponseWrapper(localName = "planDeliveryResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning", className = "stubs.planning.PlanDeliveryResponse")
    public void planDelivery(
        @WebParam(name = "drone-id", targetNamespace = "")
        int droneId,
        @WebParam(name = "tracking-number", targetNamespace = "")
        java.lang.String trackingNumber,
        @WebParam(name = "shipping-time", targetNamespace = "")
        java.lang.String shippingTime
    ) throws UnknownDroneException_Exception, UnknownPackageException_Exception;
}
