
package stubs.planning;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T12:51:13.761+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownPackageException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning")
public class UnknownPackageException_Exception extends Exception {
    
    private stubs.planning.UnknownPackageException unknownPackageException;

    public UnknownPackageException_Exception() {
        super();
    }
    
    public UnknownPackageException_Exception(String message) {
        super(message);
    }
    
    public UnknownPackageException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownPackageException_Exception(String message, stubs.planning.UnknownPackageException unknownPackageException) {
        super(message);
        this.unknownPackageException = unknownPackageException;
    }

    public UnknownPackageException_Exception(String message, stubs.planning.UnknownPackageException unknownPackageException, Throwable cause) {
        super(message, cause);
        this.unknownPackageException = unknownPackageException;
    }

    public stubs.planning.UnknownPackageException getFaultInfo() {
        return this.unknownPackageException;
    }
}
