
package stubs.planning;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T13:16:56.767+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownDeliveryException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/accounting")
public class UnknownDeliveryException extends Exception {
    
    private fr.unice.polytech.si._4a.isa.dd.team_h.accounting.UnknownDeliveryException unknownDeliveryException;

    public UnknownDeliveryException() {
        super();
    }
    
    public UnknownDeliveryException(String message) {
        super(message);
    }
    
    public UnknownDeliveryException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDeliveryException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.accounting.UnknownDeliveryException unknownDeliveryException) {
        super(message);
        this.unknownDeliveryException = unknownDeliveryException;
    }

    public UnknownDeliveryException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.accounting.UnknownDeliveryException unknownDeliveryException, Throwable cause) {
        super(message, cause);
        this.unknownDeliveryException = unknownDeliveryException;
    }

    public fr.unice.polytech.si._4a.isa.dd.team_h.accounting.UnknownDeliveryException getFaultInfo() {
        return this.unknownDeliveryException;
    }
}
