
package stubs.planning;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-19T12:07:45.351+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownDeliveryStateException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/plannings")
public class UnknownDeliveryStateException extends Exception {
    
    private fr.unice.polytech.si._4a.isa.dd.team_h.plannings.UnknownDeliveryStateException unknownDeliveryStateException;

    public UnknownDeliveryStateException() {
        super();
    }
    
    public UnknownDeliveryStateException(String message) {
        super(message);
    }
    
    public UnknownDeliveryStateException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDeliveryStateException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.plannings.UnknownDeliveryStateException unknownDeliveryStateException) {
        super(message);
        this.unknownDeliveryStateException = unknownDeliveryStateException;
    }

    public UnknownDeliveryStateException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.plannings.UnknownDeliveryStateException unknownDeliveryStateException, Throwable cause) {
        super(message, cause);
        this.unknownDeliveryStateException = unknownDeliveryStateException;
    }

    public fr.unice.polytech.si._4a.isa.dd.team_h.plannings.UnknownDeliveryStateException getFaultInfo() {
        return this.unknownDeliveryStateException;
    }
}
