
package stubs.planning;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-18T23:52:27.808+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownDeliveryStateException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning")
public class UnknownDeliveryStateException_Exception extends Exception {
    
    private stubs.planning.UnknownDeliveryStateException unknownDeliveryStateException;

    public UnknownDeliveryStateException_Exception() {
        super();
    }
    
    public UnknownDeliveryStateException_Exception(String message) {
        super(message);
    }
    
    public UnknownDeliveryStateException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDeliveryStateException_Exception(String message, stubs.planning.UnknownDeliveryStateException unknownDeliveryStateException) {
        super(message);
        this.unknownDeliveryStateException = unknownDeliveryStateException;
    }

    public UnknownDeliveryStateException_Exception(String message, stubs.planning.UnknownDeliveryStateException unknownDeliveryStateException, Throwable cause) {
        super(message, cause);
        this.unknownDeliveryStateException = unknownDeliveryStateException;
    }

    public stubs.planning.UnknownDeliveryStateException getFaultInfo() {
        return this.unknownDeliveryStateException;
    }
}
