
package stubs.planning;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-14T20:56:25.251+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownDroneException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning")
public class UnknownDroneException_Exception extends Exception {
    
    private stubs.planning.UnknownDroneException unknownDroneException;

    public UnknownDroneException_Exception() {
        super();
    }
    
    public UnknownDroneException_Exception(String message) {
        super(message);
    }
    
    public UnknownDroneException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDroneException_Exception(String message, stubs.planning.UnknownDroneException unknownDroneException) {
        super(message);
        this.unknownDroneException = unknownDroneException;
    }

    public UnknownDroneException_Exception(String message, stubs.planning.UnknownDroneException unknownDroneException, Throwable cause) {
        super(message, cause);
        this.unknownDroneException = unknownDroneException;
    }

    public stubs.planning.UnknownDroneException getFaultInfo() {
        return this.unknownDroneException;
    }
}
