version: '2.1'

services:

  # The Drone Delivery service, a J2E system
  dd_system:
    image: livrair/dd-int
    container_name: dd_system
    environment:
      - map_host=dd_partners
      - map_port=9090
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - external_partners
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # The external partners, implemented as .Net services
  external_partners:
    image: livrair/dd-ext
    container_name: dd_partners
    expose:
        - "9090"
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # A simple java CLI
  dd_client_boss_cli:
    image: livrair/dd-client-boss_cli
    container_name: dd_client_boss_cli
    command: "dd_system 8080"
    volumes:
      - .:/host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true

  dd_client_chargeur_cli:
    image: livrair/dd-client-chargeur_cli
    container_name: dd_client_chargeur_cli
    command: "dd_system 8080"
    volumes:
      - .:/host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true

  dd_client_garagiste_cli:
    image: livrair/dd-client-garagiste_cli
    container_name: dd_client_garagiste_cli
    command: "dd_system 8080"
    volumes:
      - .:/host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true

  dd_client_gestionnaire_cli:
    image: livrair/dd-client-gestionnaire_cli
    container_name: dd_client_gestionnaire_cli
    command: "dd_system 8080"
    volumes:
      - .:/host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true

  dd_client_manutentionnaire_cli:
    image: livrair/dd-client-manutentionnaire_cli
    container_name: dd_client_manutentionnaire_cli
    command: "dd_system 8080"
    volumes:
      - .:/host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true

  dd_client_service_client_cli:
    image: livrair/dd-client-service_client_cli
    container_name: dd_client_service_client_cli
    command: "dd_system 8080"
    volumes:
      - .:/host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true

  dd_client_integration_tests_cli:
    image: livrair/dd-client-integration_tests_cli
    container_name: dd_client_integration_tests_cli
    command: "dd_system 8080"
    volumes:
      - .:/host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true