package stubs.ratings;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-04-24T12:06:17.553+02:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "CommentPostingWebServiceImplService", 
                  wsdlLocation = "file:/C:/Users/dqminh/Documents/Personnel/Etude/S8/ISA & DevOps/H20 Team/projet-isa-devops-20-team-H-20/clients/Client/src/main/java/stubs/ratings/RatingWS.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating") 
public class CommentPostingWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", "CommentPostingWebServiceImplService");
    public final static QName CommentPostingWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", "CommentPostingWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/dqminh/Documents/Personnel/Etude/S8/ISA & DevOps/H20 Team/projet-isa-devops-20-team-H-20/clients/Client/src/main/java/stubs/ratings/RatingWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommentPostingWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/dqminh/Documents/Personnel/Etude/S8/ISA & DevOps/H20 Team/projet-isa-devops-20-team-H-20/clients/Client/src/main/java/stubs/ratings/RatingWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommentPostingWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommentPostingWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommentPostingWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CommentPostingWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CommentPostingWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CommentPostingWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CommentPostingWebService
     */
    @WebEndpoint(name = "CommentPostingWebServiceImplPort")
    public CommentPostingWebService getCommentPostingWebServiceImplPort() {
        return super.getPort(CommentPostingWebServiceImplPort, CommentPostingWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommentPostingWebService
     */
    @WebEndpoint(name = "CommentPostingWebServiceImplPort")
    public CommentPostingWebService getCommentPostingWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CommentPostingWebServiceImplPort, CommentPostingWebService.class, features);
    }

}
