
package stubs.ratings;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-04-24T12:06:17.394+02:00
 * Generated source version: 2.7.9
 * 
 */
public final class CommentPostingWebService_CommentPostingWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", "CommentPostingWebServiceImplService");

    private CommentPostingWebService_CommentPostingWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CommentPostingWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CommentPostingWebServiceImplService ss = new CommentPostingWebServiceImplService(wsdlURL, SERVICE_NAME);
        CommentPostingWebService port = ss.getCommentPostingWebServiceImplPort();  
        
        {
        System.out.println("Invoking findAllComments...");
        java.util.List<stubs.ratings.Comment> _findAllComments__return = port.findAllComments();
        System.out.println("findAllComments.result=" + _findAllComments__return);


        }
        {
        System.out.println("Invoking createComment...");
        java.lang.String _createComment_packageTrackingNumber = "";
        int _createComment_rating = 0;
        java.lang.String _createComment_content = "";
        try {
            stubs.ratings.Comment _createComment__return = port.createComment(_createComment_packageTrackingNumber, _createComment_rating, _createComment_content);
            System.out.println("createComment.result=" + _createComment__return);

        } catch (UnknownDeliveryException_Exception e) { 
            System.out.println("Expected exception: UnknownDeliveryException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteComment...");
        java.lang.String _deleteComment_packageTrackingNumber = "";
        try {
            boolean _deleteComment__return = port.deleteComment(_deleteComment_packageTrackingNumber);
            System.out.println("deleteComment.result=" + _deleteComment__return);

        } catch (UnknownCommentException_Exception e) { 
            System.out.println("Expected exception: UnknownCommentException has occurred.");
            System.out.println(e.toString());
        } catch (UnknownDeliveryException_Exception e) { 
            System.out.println("Expected exception: UnknownDeliveryException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findCommentForPackage...");
        java.lang.String _findCommentForPackage_packageId = "";
        try {
            stubs.ratings.Comment _findCommentForPackage__return = port.findCommentForPackage(_findCommentForPackage_packageId);
            System.out.println("findCommentForPackage.result=" + _findCommentForPackage__return);

        } catch (UnknownCommentException_Exception e) { 
            System.out.println("Expected exception: UnknownCommentException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findCommentForSupplier...");
        java.lang.String _findCommentForSupplier_supplierName = "";
        try {
            java.util.List<stubs.ratings.Comment> _findCommentForSupplier__return = port.findCommentForSupplier(_findCommentForSupplier_supplierName);
            System.out.println("findCommentForSupplier.result=" + _findCommentForSupplier__return);

        } catch (UnknownSupplierException_Exception e) { 
            System.out.println("Expected exception: UnknownSupplierException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
