package stubs.ratings;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-04-24T12:06:17.546+02:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", name = "CommentPostingWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface CommentPostingWebService {

    @WebMethod
    @RequestWrapper(localName = "findAllComments", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.FindAllComments")
    @ResponseWrapper(localName = "findAllCommentsResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.FindAllCommentsResponse")
    @WebResult(name = "comment_list", targetNamespace = "")
    public java.util.List<stubs.ratings.Comment> findAllComments();

    @WebMethod
    @RequestWrapper(localName = "createComment", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.CreateComment")
    @ResponseWrapper(localName = "createCommentResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.CreateCommentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public stubs.ratings.Comment createComment(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber,
        @WebParam(name = "rating", targetNamespace = "")
        int rating,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    ) throws UnknownDeliveryException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteComment", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.DeleteComment")
    @ResponseWrapper(localName = "deleteCommentResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.DeleteCommentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteComment(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber
    ) throws UnknownCommentException_Exception, UnknownDeliveryException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findCommentForPackage", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.FindCommentForPackage")
    @ResponseWrapper(localName = "findCommentForPackageResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.FindCommentForPackageResponse")
    @WebResult(name = "comment", targetNamespace = "")
    public stubs.ratings.Comment findCommentForPackage(
        @WebParam(name = "packageId", targetNamespace = "")
        java.lang.String packageId
    ) throws UnknownCommentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findCommentForSupplier", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.FindCommentForSupplier")
    @ResponseWrapper(localName = "findCommentForSupplierResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating", className = "stubs.ratings.FindCommentForSupplierResponse")
    @WebResult(name = "supplier_comments", targetNamespace = "")
    public java.util.List<stubs.ratings.Comment> findCommentForSupplier(
        @WebParam(name = "supplierName", targetNamespace = "")
        java.lang.String supplierName
    ) throws UnknownSupplierException_Exception;
}
