
package stubs.ratings;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-04-24T12:06:17.535+02:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "UnknownCommentException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/rating")
public class UnknownCommentException_Exception extends Exception {
    
    private stubs.ratings.UnknownCommentException unknownCommentException;

    public UnknownCommentException_Exception() {
        super();
    }
    
    public UnknownCommentException_Exception(String message) {
        super(message);
    }
    
    public UnknownCommentException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownCommentException_Exception(String message, stubs.ratings.UnknownCommentException unknownCommentException) {
        super(message);
        this.unknownCommentException = unknownCommentException;
    }

    public UnknownCommentException_Exception(String message, stubs.ratings.UnknownCommentException unknownCommentException, Throwable cause) {
        super(message, cause);
        this.unknownCommentException = unknownCommentException;
    }

    public stubs.ratings.UnknownCommentException getFaultInfo() {
        return this.unknownCommentException;
    }
}
