package fr.unice.polytech.si._4a.isa.dd.team_h.packages;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T12:34:43.737+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", name = "PackageRegistrationWebService")
@XmlSeeAlso({ObjectFactory.class, stubs.packages.ObjectFactory.class, fr.unice.polytech.si._4a.isa.dd.team_h.planning.ObjectFactory.class})
public interface PackageRegistrationWebService {

    @WebMethod
    @RequestWrapper(localName = "registerPackage", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "fr.unice.polytech.si._4a.isa.dd.team_h.packages.RegisterPackage")
    @ResponseWrapper(localName = "registerPackageResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "fr.unice.polytech.si._4a.isa.dd.team_h.packages.RegisterPackageResponse")
    public void registerPackage(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber,
        @WebParam(name = "supplierName", targetNamespace = "")
        java.lang.String supplierName,
        @WebParam(name = "weight", targetNamespace = "")
        float weight,
        @WebParam(name = "destination", targetNamespace = "")
        java.lang.String destination
    ) throws UnknownSupplierException, AlreadyExistingPackageException;

    @WebMethod
    @RequestWrapper(localName = "deletePackage", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "fr.unice.polytech.si._4a.isa.dd.team_h.packages.DeletePackage")
    @ResponseWrapper(localName = "deletePackageResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "fr.unice.polytech.si._4a.isa.dd.team_h.packages.DeletePackageResponse")
    public void deletePackage(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber
    ) throws UnknownPackageException;

    @WebMethod
    @RequestWrapper(localName = "editPackage", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "fr.unice.polytech.si._4a.isa.dd.team_h.packages.EditPackage")
    @ResponseWrapper(localName = "editPackageResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "fr.unice.polytech.si._4a.isa.dd.team_h.packages.EditPackageResponse")
    public void editPackage(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber,
        @WebParam(name = "supplierName", targetNamespace = "")
        java.lang.String supplierName,
        @WebParam(name = "weight", targetNamespace = "")
        float weight,
        @WebParam(name = "destination", targetNamespace = "")
        java.lang.String destination
    ) throws UnknownSupplierException, UnknownPackageException;
}
