
package stubs.packages;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T13:25:09.880+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "AlreadyExistingPackageException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages")
public class AlreadyExistingPackageException_Exception extends Exception {
    
    private stubs.packages.AlreadyExistingPackageException alreadyExistingPackageException;

    public AlreadyExistingPackageException_Exception() {
        super();
    }
    
    public AlreadyExistingPackageException_Exception(String message) {
        super(message);
    }
    
    public AlreadyExistingPackageException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyExistingPackageException_Exception(String message, stubs.packages.AlreadyExistingPackageException alreadyExistingPackageException) {
        super(message);
        this.alreadyExistingPackageException = alreadyExistingPackageException;
    }

    public AlreadyExistingPackageException_Exception(String message, stubs.packages.AlreadyExistingPackageException alreadyExistingPackageException, Throwable cause) {
        super(message, cause);
        this.alreadyExistingPackageException = alreadyExistingPackageException;
    }

    public stubs.packages.AlreadyExistingPackageException getFaultInfo() {
        return this.alreadyExistingPackageException;
    }
}
