package stubs.packages;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T13:16:56.925+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "PackageRegistrationWebServiceImplService", 
                  wsdlLocation = "file:/C:/Users/damin/Documents/cours/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/resources/PackageRegistrationWebServiceImpl.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages") 
public class PackageRegistrationWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", "PackageRegistrationWebServiceImplService");
    public final static QName PackageRegistrationWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", "PackageRegistrationWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/damin/Documents/cours/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/resources/PackageRegistrationWebServiceImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PackageRegistrationWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/damin/Documents/cours/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/resources/PackageRegistrationWebServiceImpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PackageRegistrationWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PackageRegistrationWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PackageRegistrationWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PackageRegistrationWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PackageRegistrationWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PackageRegistrationWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PackageRegistrationWebService
     */
    @WebEndpoint(name = "PackageRegistrationWebServiceImplPort")
    public PackageRegistrationWebService getPackageRegistrationWebServiceImplPort() {
        return super.getPort(PackageRegistrationWebServiceImplPort, PackageRegistrationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PackageRegistrationWebService
     */
    @WebEndpoint(name = "PackageRegistrationWebServiceImplPort")
    public PackageRegistrationWebService getPackageRegistrationWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PackageRegistrationWebServiceImplPort, PackageRegistrationWebService.class, features);
    }

}
