package stubs.packages;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-18T23:52:27.970+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", name = "PackageRegistrationWebService")
@XmlSeeAlso({ObjectFactory.class, fr.unice.polytech.si._4a.isa.dd.team_h.planning.ObjectFactory.class})
public interface PackageRegistrationWebService {

    @WebMethod
    @RequestWrapper(localName = "registerPackage", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "stubs.packages.RegisterPackage")
    @ResponseWrapper(localName = "registerPackageResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "stubs.packages.RegisterPackageResponse")
    public void registerPackage(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber,
        @WebParam(name = "supplierName", targetNamespace = "")
        java.lang.String supplierName,
        @WebParam(name = "weight", targetNamespace = "")
        float weight,
        @WebParam(name = "destination", targetNamespace = "")
        java.lang.String destination
    ) throws UnknownSupplierException_Exception, AlreadyExistingPackageException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deletePackage", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "stubs.packages.DeletePackage")
    @ResponseWrapper(localName = "deletePackageResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "stubs.packages.DeletePackageResponse")
    public void deletePackage(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber
    ) throws UnknownPackageException;

    @WebMethod
    @RequestWrapper(localName = "editPackage", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "stubs.packages.EditPackage")
    @ResponseWrapper(localName = "editPackageResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages", className = "stubs.packages.EditPackageResponse")
    public void editPackage(
        @WebParam(name = "packageTrackingNumber", targetNamespace = "")
        java.lang.String packageTrackingNumber,
        @WebParam(name = "supplierName", targetNamespace = "")
        java.lang.String supplierName,
        @WebParam(name = "weight", targetNamespace = "")
        float weight,
        @WebParam(name = "destination", targetNamespace = "")
        java.lang.String destination
    ) throws UnknownSupplierException_Exception, UnknownPackageException;
}
