
package stubs.packages;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T13:16:56.914+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownPackageException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning")
public class UnknownPackageException extends Exception {
    
    private fr.unice.polytech.si._4a.isa.dd.team_h.planning.UnknownPackageException unknownPackageException;

    public UnknownPackageException() {
        super();
    }
    
    public UnknownPackageException(String message) {
        super(message);
    }
    
    public UnknownPackageException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownPackageException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.planning.UnknownPackageException unknownPackageException) {
        super(message);
        this.unknownPackageException = unknownPackageException;
    }

    public UnknownPackageException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.planning.UnknownPackageException unknownPackageException, Throwable cause) {
        super(message, cause);
        this.unknownPackageException = unknownPackageException;
    }

    public fr.unice.polytech.si._4a.isa.dd.team_h.planning.UnknownPackageException getFaultInfo() {
        return this.unknownPackageException;
    }
}
