
package stubs.packages;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T11:09:34.951+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownSupplierException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/package")
public class UnknownSupplierException_Exception extends Exception {
    
    private stubs.packages.UnknownSupplierException unknownSupplierException;

    public UnknownSupplierException_Exception() {
        super();
    }
    
    public UnknownSupplierException_Exception(String message) {
        super(message);
    }
    
    public UnknownSupplierException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownSupplierException_Exception(String message, stubs.packages.UnknownSupplierException unknownSupplierException) {
        super(message);
        this.unknownSupplierException = unknownSupplierException;
    }

    public UnknownSupplierException_Exception(String message, stubs.packages.UnknownSupplierException unknownSupplierException, Throwable cause) {
        super(message, cause);
        this.unknownSupplierException = unknownSupplierException;
    }

    public stubs.packages.UnknownSupplierException getFaultInfo() {
        return this.unknownSupplierException;
    }
}
