
package stubs.accounting;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-17T08:51:20.675+01:00
 * Generated source version: 2.7.9
 * 
 */
public final class AccountingWebService_AccountingWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/accounting", "AccountingWebServiceImplService");

    private AccountingWebService_AccountingWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AccountingWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AccountingWebServiceImplService ss = new AccountingWebServiceImplService(wsdlURL, SERVICE_NAME);
        AccountingWebService port = ss.getAccountingWebServiceImplPort();  
        
        {
        System.out.println("Invoking findInvoicesForSupplier...");
        stubs.accounting.Supplier _findInvoicesForSupplier_supplier = null;
        try {
            java.util.List<stubs.accounting.Invoice> _findInvoicesForSupplier__return = port.findInvoicesForSupplier(_findInvoicesForSupplier_supplier);
            System.out.println("findInvoicesForSupplier.result=" + _findInvoicesForSupplier__return);

        } catch (UnknownSupplierException_Exception e) { 
            System.out.println("Expected exception: UnknownSupplierException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking generateInvoicesForAllSuppliers...");
        port.generateInvoicesForAllSuppliers();


        }
        {
        System.out.println("Invoking register...");
        java.lang.String _register_name = "";
        java.lang.String _register_contact = "";
        try {
            port.register(_register_name, _register_contact);

        } catch (AlreadyExistingSupplierException_Exception e) { 
            System.out.println("Expected exception: AlreadyExistingSupplierException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking generateInvoiceFor...");
        stubs.accounting.Supplier _generateInvoiceFor_supplier = null;
        try {
            port.generateInvoiceFor(_generateInvoiceFor_supplier);

        } catch (UnknownSupplierException_Exception e) { 
            System.out.println("Expected exception: UnknownSupplierException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findAllUnpaidInvoices...");
        java.util.List<stubs.accounting.Invoice> _findAllUnpaidInvoices__return = port.findAllUnpaidInvoices();
        System.out.println("findAllUnpaidInvoices.result=" + _findAllUnpaidInvoices__return);


        }
        {
        System.out.println("Invoking findByName...");
        java.lang.String _findByName_name = "";
        try {
            stubs.accounting.Supplier _findByName__return = port.findByName(_findByName_name);
            System.out.println("findByName.result=" + _findByName__return);

        } catch (UnknownSupplierException_Exception e) { 
            System.out.println("Expected exception: UnknownSupplierException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
