package stubs.accounting;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-17T08:51:20.749+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "AccountingWebServiceImplService", 
                  wsdlLocation = "file:/C:/Users/user/Documents/Personnel/Etude/S8/ISA & DevOps/H20 Team/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/java/stubs/accounting/AccountingWebServiceImpl.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/accounting") 
public class AccountingWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/accounting", "AccountingWebServiceImplService");
    public final static QName AccountingWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/accounting", "AccountingWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/user/Documents/Personnel/Etude/S8/ISA & DevOps/H20 Team/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/java/stubs/accounting/AccountingWebServiceImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccountingWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/user/Documents/Personnel/Etude/S8/ISA & DevOps/H20 Team/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/java/stubs/accounting/AccountingWebServiceImpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccountingWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccountingWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountingWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AccountingWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AccountingWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AccountingWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AccountingWebService
     */
    @WebEndpoint(name = "AccountingWebServiceImplPort")
    public AccountingWebService getAccountingWebServiceImplPort() {
        return super.getPort(AccountingWebServiceImplPort, AccountingWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountingWebService
     */
    @WebEndpoint(name = "AccountingWebServiceImplPort")
    public AccountingWebService getAccountingWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AccountingWebServiceImplPort, AccountingWebService.class, features);
    }

}
