
package stubs.accounting;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-17T08:51:20.724+01:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "UnknownSupplierException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/packages")
public class UnknownSupplierException_Exception extends Exception {
    
    private stubs.accounting.UnknownSupplierException unknownSupplierException;

    public UnknownSupplierException_Exception() {
        super();
    }
    
    public UnknownSupplierException_Exception(String message) {
        super(message);
    }
    
    public UnknownSupplierException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownSupplierException_Exception(String message, stubs.accounting.UnknownSupplierException unknownSupplierException) {
        super(message);
        this.unknownSupplierException = unknownSupplierException;
    }

    public UnknownSupplierException_Exception(String message, stubs.accounting.UnknownSupplierException unknownSupplierException, Throwable cause) {
        super(message, cause);
        this.unknownSupplierException = unknownSupplierException;
    }

    public stubs.accounting.UnknownSupplierException getFaultInfo() {
        return this.unknownSupplierException;
    }
}
