
package stubs.rating;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-04-24T18:14:46.405+02:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "UnknownDeliveryException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/accounting")
public class UnknownDeliveryException_Exception extends Exception {
    
    private stubs.rating.UnknownDeliveryException unknownDeliveryException;

    public UnknownDeliveryException_Exception() {
        super();
    }
    
    public UnknownDeliveryException_Exception(String message) {
        super(message);
    }
    
    public UnknownDeliveryException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDeliveryException_Exception(String message, stubs.rating.UnknownDeliveryException unknownDeliveryException) {
        super(message);
        this.unknownDeliveryException = unknownDeliveryException;
    }

    public UnknownDeliveryException_Exception(String message, stubs.rating.UnknownDeliveryException unknownDeliveryException, Throwable cause) {
        super(message, cause);
        this.unknownDeliveryException = unknownDeliveryException;
    }

    public stubs.rating.UnknownDeliveryException getFaultInfo() {
        return this.unknownDeliveryException;
    }
}
