
package stubs.drone;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T12:51:14.081+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "AlreadyExistingDroneException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones")
public class AlreadyExistingDroneException_Exception extends Exception {
    
    private stubs.drone.AlreadyExistingDroneException alreadyExistingDroneException;

    public AlreadyExistingDroneException_Exception() {
        super();
    }
    
    public AlreadyExistingDroneException_Exception(String message) {
        super(message);
    }
    
    public AlreadyExistingDroneException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyExistingDroneException_Exception(String message, stubs.drone.AlreadyExistingDroneException alreadyExistingDroneException) {
        super(message);
        this.alreadyExistingDroneException = alreadyExistingDroneException;
    }

    public AlreadyExistingDroneException_Exception(String message, stubs.drone.AlreadyExistingDroneException alreadyExistingDroneException, Throwable cause) {
        super(message, cause);
        this.alreadyExistingDroneException = alreadyExistingDroneException;
    }

    public stubs.drone.AlreadyExistingDroneException getFaultInfo() {
        return this.alreadyExistingDroneException;
    }
}
