package stubs.drone;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-15T18:55:03.912+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drone", name = "DroneFleetManagementWebService")
@XmlSeeAlso({ObjectFactory.class, fr.unice.polytech.si._4a.isa.dd.team_h.planning.ObjectFactory.class})
public interface DroneFleetManagementWebService {

    @WebMethod
    @RequestWrapper(localName = "addDrone", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drone", className = "stubs.drone.AddDrone")
    @ResponseWrapper(localName = "addDroneResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drone", className = "stubs.drone.AddDroneResponse")
    public void addDrone(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "weightCapacity", targetNamespace = "")
        float weightCapacity
    );

    @WebMethod
    @RequestWrapper(localName = "removeDrone", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drone", className = "stubs.drone.RemoveDrone")
    @ResponseWrapper(localName = "removeDroneResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drone", className = "stubs.drone.RemoveDroneResponse")
    public void removeDrone(
        @WebParam(name = "id", targetNamespace = "")
        int id
    ) throws UnknownDroneException;
}
