package stubs.drone;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-19T12:07:45.720+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "DroneFleetManagementWebServiceImplService", 
                  wsdlLocation = "file:/C:/Users/Triagon/Desktop/Work/Polytech/ISA-DevOps/DevOps/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/resources/DroneFleetManagementWebServiceImpl.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones") 
public class DroneFleetManagementWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", "DroneFleetManagementWebServiceImplService");
    public final static QName DroneFleetManagementWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", "DroneFleetManagementWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Triagon/Desktop/Work/Polytech/ISA-DevOps/DevOps/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/resources/DroneFleetManagementWebServiceImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DroneFleetManagementWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Triagon/Desktop/Work/Polytech/ISA-DevOps/DevOps/projet-isa-devops-20-team-H-20/DroneDeliveryClient/src/main/resources/DroneFleetManagementWebServiceImpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DroneFleetManagementWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DroneFleetManagementWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DroneFleetManagementWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DroneFleetManagementWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DroneFleetManagementWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DroneFleetManagementWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DroneFleetManagementWebService
     */
    @WebEndpoint(name = "DroneFleetManagementWebServiceImplPort")
    public DroneFleetManagementWebService getDroneFleetManagementWebServiceImplPort() {
        return super.getPort(DroneFleetManagementWebServiceImplPort, DroneFleetManagementWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DroneFleetManagementWebService
     */
    @WebEndpoint(name = "DroneFleetManagementWebServiceImplPort")
    public DroneFleetManagementWebService getDroneFleetManagementWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DroneFleetManagementWebServiceImplPort, DroneFleetManagementWebService.class, features);
    }

}
