package stubs.drone;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T12:51:14.094+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", name = "DroneFleetManagementWebService")
@XmlSeeAlso({ObjectFactory.class, fr.unice.polytech.si._4a.isa.dd.team_h.planning.ObjectFactory.class})
public interface DroneFleetManagementWebService {

    @WebMethod
    @RequestWrapper(localName = "addDrone", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", className = "stubs.drone.AddDrone")
    @ResponseWrapper(localName = "addDroneResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", className = "stubs.drone.AddDroneResponse")
    public void addDrone(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "weightCapacity", targetNamespace = "")
        float weightCapacity
    ) throws AlreadyExistingDroneException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDrone", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", className = "stubs.drone.GetDrone")
    @ResponseWrapper(localName = "getDroneResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", className = "stubs.drone.GetDroneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public stubs.drone.Drone getDrone(
        @WebParam(name = "id", targetNamespace = "")
        int id
    ) throws UnknownDroneException;

    @WebMethod
    @RequestWrapper(localName = "removeDrone", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", className = "stubs.drone.RemoveDrone")
    @ResponseWrapper(localName = "removeDroneResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", className = "stubs.drone.RemoveDroneResponse")
    public void removeDrone(
        @WebParam(name = "id", targetNamespace = "")
        int id
    ) throws UnknownDroneException;

    @WebMethod
    @RequestWrapper(localName = "editDroneStatus", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", className = "stubs.drone.EditDroneStatus")
    @ResponseWrapper(localName = "editDroneStatusResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones", className = "stubs.drone.EditDroneStatusResponse")
    public void editDroneStatus(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status
    ) throws UnknownDroneStateException_Exception, UnknownDroneException;
}
