
package stubs.drone;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-19T12:51:18.113+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownDroneStateException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones")
public class UnknownDroneStateException_Exception extends Exception {
    
    private stubs.drone.UnknownDroneStateException unknownDroneStateException;

    public UnknownDroneStateException_Exception() {
        super();
    }
    
    public UnknownDroneStateException_Exception(String message) {
        super(message);
    }
    
    public UnknownDroneStateException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDroneStateException_Exception(String message, stubs.drone.UnknownDroneStateException unknownDroneStateException) {
        super(message);
        this.unknownDroneStateException = unknownDroneStateException;
    }

    public UnknownDroneStateException_Exception(String message, stubs.drone.UnknownDroneStateException unknownDroneStateException, Throwable cause) {
        super(message, cause);
        this.unknownDroneStateException = unknownDroneStateException;
    }

    public stubs.drone.UnknownDroneStateException getFaultInfo() {
        return this.unknownDroneStateException;
    }
}
