
package stubs.drone;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T12:51:14.086+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownDroneException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/planning")
public class UnknownDroneException extends Exception {
    
    private fr.unice.polytech.si._4a.isa.dd.team_h.planning.UnknownDroneException unknownDroneException;

    public UnknownDroneException() {
        super();
    }
    
    public UnknownDroneException(String message) {
        super(message);
    }
    
    public UnknownDroneException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDroneException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.planning.UnknownDroneException unknownDroneException) {
        super(message);
        this.unknownDroneException = unknownDroneException;
    }

    public UnknownDroneException(String message, fr.unice.polytech.si._4a.isa.dd.team_h.planning.UnknownDroneException unknownDroneException, Throwable cause) {
        super(message, cause);
        this.unknownDroneException = unknownDroneException;
    }

    public fr.unice.polytech.si._4a.isa.dd.team_h.planning.UnknownDroneException getFaultInfo() {
        return this.unknownDroneException;
    }
}
