
package fr.unice.polytech.si._4a.isa.dd.team_h.drones;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-03-17T12:38:59.240+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "UnknownDroneStateException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dd/team-h/drones")
public class UnknownDroneStateException_Exception extends Exception {
    
    private fr.unice.polytech.si._4a.isa.dd.team_h.drones.UnknownDroneStateException unknownDroneStateException;

    public UnknownDroneStateException_Exception() {
        super();
    }
    
    public UnknownDroneStateException_Exception(String message) {
        super(message);
    }
    
    public UnknownDroneStateException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDroneStateException_Exception(String message, fr.unice.polytech.si._4a.isa.dd.team_h.drones.UnknownDroneStateException unknownDroneStateException) {
        super(message);
        this.unknownDroneStateException = unknownDroneStateException;
    }

    public UnknownDroneStateException_Exception(String message, fr.unice.polytech.si._4a.isa.dd.team_h.drones.UnknownDroneStateException unknownDroneStateException, Throwable cause) {
        super(message, cause);
        this.unknownDroneStateException = unknownDroneStateException;
    }

    public fr.unice.polytech.si._4a.isa.dd.team_h.drones.UnknownDroneStateException getFaultInfo() {
        return this.unknownDroneStateException;
    }
}
